name: auction_app
description: A new Flutter project.

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  firebase_core: ^2.15.0
  firebase_auth: ^4.7.0
  google_sign_in: ^6.1.4
  cloud_firestore: ^4.8.3
  image_picker: ^1.0.1
  firebase_storage: ^11.2.5
  liquid_pull_to_refresh: ^3.0.1
  path: ^1.8.3

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0


flutter:


  uses-material-design: true


  assets:
      - images/google.png
      - images/logo.png



  fonts:
   - family: Pacifico
     fonts:
      - asset: fonts/Pacifico-Regular.ttf
      

   - family: SourceSans3
     fonts:
      - asset: fonts/SourceSans3-Regular.ttf
