name: CI

on:
  push:
    branches:
      - main

jobs:
  flutter_test:
    name: Run Flutter Analyze and Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - run: flutter pub get

      - name: Analyze Code (fail only on errors)
        run: |
          set +e
          flutter analyze > analysis.log
          ANALYZE_EXIT=$?
          cat analysis.log
          if grep -q "error •" analysis.log; then
            echo "❌ Found errors in flutter analyze"
            exit 1
          else
            echo "✅ No errors found"
            exit 0
          fi

      # Skip tests if test folder is missing
      - name: Run Tests (skip if no tests)
        run: |
          if [ -d "test" ]; then
            flutter test
          else
            echo "No tests found, skipping..."
          fi

  build_ios:
    name: Build Flutter (iOS)
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - run: flutter pub get
      - run: flutter clean

      # Ensure iOS 13 deployment target
      - name: Set iOS Deployment Target to 13.0
        run: |
          sed -i '' 's/platform :ios, .*/platform :ios, "13.0"/' ios/Podfile || echo 'platform :ios, "13.0"' >> ios/Podfile

      - run: flutter build ios --release --no-codesign

  build_appbundle:
    name: Build Flutter (Android)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - run: flutter pub get
      - run: flutter clean

      - name: Build Android App Bundle
        run: flutter build appbundle
        env:
          GRADLE_OPTS: "-Xmx4g"
