name: CI

on:
  push:
    branches:
      - main

jobs:
  flutter_test:
    name: Run Flutter Test and Analyze
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - run: flutter pub get

      - name: Analyze Code (fail only on errors)
        run: |
          flutter analyze > analysis.log
          cat analysis.log
          if grep -q "error •" analysis.log; then
            echo "❌ Found errors in flutter analyze"
            exit 1
          else
            echo "✅ No errors found"
          fi

      - run: flutter test


  build_ios:
    name: Build Flutter (iOS)
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - run: flutter pub get
      - run: flutter clean
      - run: flutter build ios --release --no-codesign


  build_appbundle:
    name: Build Flutter (Android)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - run: flutter pub get
      - run: flutter clean
      - run: flutter build appbundle
